---
- name: update node1 servers
  hosts: node1
  
  tasks:
   - name: create /opt/devops directory
     file:
       path: /home/fedora/opt/devops/new_dir
       state: directory

   - name: create /opt/devops directory
     file:
       path: /home/fedora/opt/devops/new_dir_1
       state: directory     

- name: update node2 servers
  hosts: node2

  tasks:
   - name: create directory
     file:
       path: /home/fedora/new_dir
       state: directory

   - name: create /opt/devops directory
     file:
       path: /home/fedora/new_dir_1
       state: directory

- name: update g2 servers
  hosts: g2

  tasks:
   - name: create directory
     file:
       path: /home/fedora/new_dir_1
       state: directory

   - name: create directory
     file:
       path: /home/fedora/new_dir_1
       state: directory
...
